### ISSUE TITLE
[SmartSign] Modifications non sauvegardées

### ISSUE THREAD

**Issue by kevinvennitti** [Theoriz/Augmenta#1]
(Je poste l'issue ici, je n'ai pas vu de repo pour SmartSign)

Lorsque je configure l'environnement de SmartSign avec le mode S (donc déplacement et rotation des éléments), cette nouvelle configuration n'est pas sauvegardée lors du prochain boot de la machine. Depuis deux jours, je dois reconfigurer la position des éléments de SmartSign tous les matins.

Causes possibles :
- L'ordinateur est éteint en _brut force_ (débranché du secteur)

**Comment by Lyptik** [comment]
Regardes si les permissions linux n'ont pas changé, si les settings doivent s'écrire dans un endroit ou le programme n'a pas les permissions d'écrire cela peut arriver.

Si l'ordinateur a été éteint brutalement, regarde aussi si Linux ne s'est pas protégé en montant la totalité de la partition en read only.

**Comment by kevinvennitti** [comment]
Quel dossier/fichier dois-je vérifier les droits ?

**Comment by kevinvennitti** [comment]
J'ai rétabli les droits d'écriture au groupe "augmenta" et ça fonctionne.

**Comment by kevinvennitti** [comment]
Non résolu, la configuration ne s'enregistre toujours pas. À quel dossier faudrait-il imposer un accès en écriture ?
